# Generated by Django 4.1.2 on 2022-10-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('sold', models.BooleanField(default=True)),
                ('year', models.DateField(null=True)),
                ('type', models.CharField(choices=[('RD', 'Records'), ('CL', 'Clothing'), ('PO', 'Posters'), ('MS', 'Miscellaneaous')], max_length=100)),
            ],
        ),
    ]
