# Generated by Django 4.1.2 on 2022-10-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Title',
            field=models.CharField(default='text', max_length=200),
            preserve_default=False,
        ),
    ]
